### ISSUE TITLE
Something got dirty, Generate Rig throws an error

### ISSUE THREAD

**Issue by rickyManalo** [UuuNyaa/blender_mmd_tools#16]
Because of various reasons, I decided to start from scratch and use blender's metarig for practicing. After setting up the rig, I hit Generate Rig and an error popped.

Generation has thrown an exception: IDProperty "mmd_bone" does not support UI data

I think this tool somehow added something to maybe the rig that Generate Rig didn't like. Generate Rig was only able to generate the IK for the feet I think and nothing more.

I'm using blender 3 btw

**Comment by UuuNyaa** [comment]
Give me detailed versions of the software you are using.

In my environment, using **Generate Rig** does not cause any problems.
- Blender v3.0.0
- MMD Tools v2.0.0
- MMD UuuNyaa Tools v1.1.12
- 
https://user-images.githubusercontent.com/70152495/147860266-c22d6c3e-8dff-49a7-916a-f4a521bf601b.mp4

**Comment by rickyManalo** [comment]
I might not have didn't mention before, but I added the metarig the normal
way using blender's own add menu. I didn't use any of the functionalities
of the mmd_tools or any of the related tools

**Comment by UuuNyaa** [comment]
> I didn't use any of the functionalities of the mmd_tools or any of the related tools

I see, however according to the error message, **mmd_tools** should be installed.
What version of **mmd_tools** are you using?

In my environment, no error occurs.
https://user-images.githubusercontent.com/70152495/147860606-d298e4b8-a92c-4e8c-a1c6-d7618c6ae756.mp4

**Comment by nagadomi** [comment]
This issue is already fixed in rigify, but not released yet.
[Rigify Error: generate rig with custom property from external addon (bpy.props.PointerProperty)](https://developer.blender.org/T92530)
https://developer.blender.org/rBA905cfc4040e71bcc60d5526506814431bd0a8e58

I was able to reproduce the error before, but I am not able to reproduce it today for unknown reasons.
If I remember correctly, when clicking `Upgrade Face Rig` before `Generate Rig`, the error did not occur.

**Comment by rickyManalo** [comment]
I was using 1.0.2. I also remembered, even when I disabled mmd_tools on the
addons, I still got the error.

**Comment by UuuNyaa** [comment]
It is probably the problem that @nagadomi pointed out.
Please wait until the fixed version is released.

**Comment by rickyManalo** [comment]
I see. I will

**Comment by lordborok** [comment]
I still get the error even when using update face rig and i also tried to get the fixed version of Rigify that should solve the issue with custom_properties. 

Its kinda confusing how to replicate the issue. First i thought it was when saved the file and re open. But that still not reliable way to reproduce the error. What i have experienced it never happens to fresh meta rig. But after some bone moving and time it suddenly wont generate a the rig. 
 
I also see this in console when "Generation has thrown an exception: IDProperty "mmd_bone" does not support UI data"

Python: Traceback (most recent call last):
  File "C:\Users\Boroko\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mmd_uuunyaa_tools\converters\armatures\panels.py", line 40, in draw
    arm_l_ik_fk = rigify_armature_object.datapaths[ControlType.ARM_L_IK_FK]
KeyError: <ControlType.ARM_L_IK_FK: 'arm_l_ik_fk'>

location: <unknown location>:-1

Might it be the UuuNyaa tool Side panel UI that break the rig generation?

**Comment by rickyManalo** [comment]
It's still there. https://drive.google.com/file/d/1SwvXkBHZAuoOjd-F_U1CwNDLwKOJ9d88/view?usp=sharing

**Comment by UuuNyaa** [comment]
@rickyManalo This error occurs when the add-ons are not installed properly.

Try the following steps:
1. Uninstall(remove) the MMD Tools
2. File ‣ Defaults ‣ Save Startup File
3. Restart Blender
4. Install latest MMD Tools (v2.1.0)

**Comment by lordborok** [comment]
> @lordborok Does the problem still occur? I would like to know the lines before and after the console message.

I seems not to be able to replicate the error anymore. Either it could be my attempt to re-install the plugin or my different attempts. Both my machines does not complain anymore.

**Comment by rickyManalo** [comment]
For me, I think, for some reason, it might also be related to the
installation or the absence of it. On my latest project, even when I don't
have the mmd_tools yet, it was already complaining about it.
Fortunately, after installing and uninstalling it, the error disappeared.

**Comment by UuuNyaa** [comment]
I have improved the stability of add-on initialization in the following commit.
https://github.com/UuuNyaa/blender_mmd_tools/commit/7ff833ba0a07392e1bab89fa8c81828ff7d18077

If you encounter the same problem, please create a new Issue.

**Comment by rickyManalo** [comment]
Thanks!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
